<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\EvaluationAnswerOption>
 */
class EvaluationAnswerOptionFactory extends Factory
{
    protected static int $i = 0;
    public function definition(): array
    {
        $answers_opt = [
            ["answerId" => 1,  "optionId" => 1],
            ["answerId" => 1,  "optionId" => 2],
            ["answerId" => 2,  "optionId" => 1],
            ["answerId" => 2,  "optionId" => 3],
            ["answerId" => 2,  "optionId" => 4],
            ["answerId" => 3,  "optionId" => 5],
            ["answerId" => 3,  "optionId" => 6],
            ["answerId" => 4,  "optionId" => 1],
            ["answerId" => 4,  "optionId" => 7],
            ["answerId" => 4,  "optionId" => 8],
            ["answerId" => 5,  "optionId" => 1],
            ["answerId" => 5,  "optionId" => 7],
            ["answerId" => 5,  "optionId" => 8],
            ["answerId" => 6,  "optionId" => 1],
            ["answerId" => 6,  "optionId" => 7],
            ["answerId" => 6,  "optionId" => 8],
            ["answerId" => 7,  "optionId" => 1],
            ["answerId" => 7,  "optionId" => 9],
            ["answerId" => 8,  "optionId" => 1],
            ["answerId" => 8,  "optionId" => 10],
            ["answerId" => 8,  "optionId" => 11],
            ["answerId" => 9,  "optionId" => 1],
            ["answerId" => 9,  "optionId" => 10],
            ["answerId" => 9,  "optionId" => 11],
            ["answerId" => 10, "optionId" => 1],
            ["answerId" => 10, "optionId" => 12],
            ["answerId" => 10, "optionId" => 13],
            ["answerId" => 11, "optionId" => 1],
            ["answerId" => 11, "optionId" => 14],
            ["answerId" => 11, "optionId" => 15],
            ["answerId" => 11, "optionId" => 16],
            ["answerId" => 12, "optionId" => 1],
            ["answerId" => 12, "optionId" => 17],
            ["answerId" => 12, "optionId" => 18],
            ["answerId" => 13, "optionId" => 1],
            ["answerId" => 13, "optionId" => 17],
            ["answerId" => 13, "optionId" => 18],
            ["answerId" => 14, "optionId" => 19],
            ["answerId" => 14, "optionId" => 20],
            ["answerId" => 15, "optionId" => 1],
            ["answerId" => 15, "optionId" => 21],
            ["answerId" => 15, "optionId" => 22],
            ["answerId" => 16, "optionId" => 23],
            ["answerId" => 16, "optionId" => 24],
            ["answerId" => 17, "optionId" => 1],
            ["answerId" => 17, "optionId" => 25],
            ["answerId" => 17, "optionId" => 26],
            ["answerId" => 18, "optionId" => 27],
            ["answerId" => 18, "optionId" => 28],
            ["answerId" => 19, "optionId" => 29],
            ["answerId" => 19, "optionId" => 30],
            ["answerId" => 20, "optionId" => 31],
            ["answerId" => 20, "optionId" => 32],
            ["answerId" => 20, "optionId" => 33],
            ["answerId" => 21, "optionId" => 31],
            ["answerId" => 21, "optionId" => 32],
            ["answerId" => 21, "optionId" => 33],
            ["answerId" => 22, "optionId" => 19],
            ["answerId" => 22, "optionId" => 20],
            ["answerId" => 23, "optionId" => 1],
            ["answerId" => 23, "optionId" => 34],
            ["answerId" => 24, "optionId" => 1],
            ["answerId" => 24, "optionId" => 35],
            ["answerId" => 24, "optionId" => 36],
            ["answerId" => 25, "optionId" => 37],
            ["answerId" => 25, "optionId" => 38],
            ["answerId" => 25, "optionId" => 39],
            ["answerId" => 25, "optionId" => 40],
            ["answerId" => 26, "optionId" => 37],
            ["answerId" => 26, "optionId" => 38],
            ["answerId" => 26, "optionId" => 39],
            ["answerId" => 26, "optionId" => 40],
            ["answerId" => 27, "optionId" => 41],
            ["answerId" => 28, "optionId" => 42],
            ["answerId" => 28, "optionId" => 43],
            ["answerId" => 29, "optionId" => 44],
            ["answerId" => 29, "optionId" => 45],
            ["answerId" => 30, "optionId" => 46],
            ["answerId" => 30, "optionId" => 47],
            ["answerId" => 30, "optionId" => 48],            
            ["answerId" => 31, "optionId" => 49],
            ["answerId" => 31, "optionId" => 50],
            ["answerId" => 32, "optionId" => 51],
            ["answerId" => 32, "optionId" => 52],
            ["answerId" => 33, "optionId" => 53],
            ["answerId" => 33, "optionId" => 54],
            ["answerId" => 34, "optionId" => 55],
            ["answerId" => 34, "optionId" => 56],
            ["answerId" => 35, "optionId" => 57],
            ["answerId" => 35, "optionId" => 58],
            ["answerId" => 36, "optionId" => 59],
            ["answerId" => 37, "optionId" => 60],
            ["answerId" => 37, "optionId" => 61],
            ["answerId" => 37, "optionId" => 62],            
            ["answerId" => 38, "optionId" => 63],
            ["answerId" => 38, "optionId" => 64],
            ["answerId" => 38, "optionId" => 65],            
            ["answerId" => 39, "optionId" => 66],
            ["answerId" => 39, "optionId" => 67],
            ["answerId" => 40, "optionId" => 19],
            ["answerId" => 40, "optionId" => 20],
            ["answerId" => 41, "optionId" => 68],
            ["answerId" => 42, "optionId" => 69],
            ["answerId" => 42, "optionId" => 70],
            ["answerId" => 42, "optionId" => 71],            
            ["answerId" => 43, "optionId" => 72],
            ["answerId" => 43, "optionId" => 73],
            ["answerId" => 43, "optionId" => 74],            
            ["answerId" => 44, "optionId" => 72],
            ["answerId" => 44, "optionId" => 73],
            ["answerId" => 44, "optionId" => 74],       
            ["answerId" => 45, "optionId" => 75],
            ["answerId" => 45, "optionId" => 76],
            ["answerId" => 45, "optionId" => 77],            
            ["answerId" => 46, "optionId" => 75],
            ["answerId" => 46, "optionId" => 76],
            ["answerId" => 46, "optionId" => 77],  
            ["answerId" => 47, "optionId" => 78],
            ["answerId" => 47, "optionId" => 79],
            ["answerId" => 47, "optionId" => 80],
            ["answerId" => 47, "optionId" => 81],
            ["answerId" => 48, "optionId" => 78],
            ["answerId" => 48, "optionId" => 79],
            ["answerId" => 48, "optionId" => 80],
            ["answerId" => 48, "optionId" => 81],
            ["answerId" => 49, "optionId" => 82],
            ["answerId" => 49, "optionId" => 83],
            ["answerId" => 50, "optionId" => 84],
            ["answerId" => 50, "optionId" => 85],
            ["answerId" => 51, "optionId" => 86],
            ["answerId" => 51, "optionId" => 87],
            ["answerId" => 52, "optionId" => 88],
            ["answerId" => 52, "optionId" => 89],
            ["answerId" => 53, "optionId" => 90],
            ["answerId" => 53, "optionId" => 91],
            ["answerId" => 54, "optionId" => 88],
            ["answerId" => 54, "optionId" => 89],
            ["answerId" => 55, "optionId" => 92],
            ["answerId" => 55, "optionId" => 93],
            ["answerId" => 56, "optionId" => 94],
            ["answerId" => 56, "optionId" => 95],
            ["answerId" => 57, "optionId" => 96],
            ["answerId" => 57, "optionId" => 97],
            ["answerId" => 58, "optionId" => 98],
            ["answerId" => 58, "optionId" => 99],
            ["answerId" => 58, "optionId" => 100],
            ["answerId" => 58, "optionId" => 101],
            ["answerId" => 58, "optionId" => 102],
            ["answerId" => 58, "optionId" => 103],
            ["answerId" => 59, "optionId" => 104],
            ["answerId" => 59, "optionId" => 105],
            ["answerId" => 59, "optionId" => 106],
            ["answerId" => 59, "optionId" => 107],
            ["answerId" => 59, "optionId" => 108],
            ["answerId" => 59, "optionId" => 109],
            ["answerId" => 60, "optionId" => 110],
            ["answerId" => 60, "optionId" => 111],
            ["answerId" => 60, "optionId" => 112],
            ["answerId" => 60, "optionId" => 113],
            ["answerId" => 60, "optionId" => 114],
            ["answerId" => 60, "optionId" => 115],
     
        ];
        
        $a = $answers_opt[ static::$i % count($answers_opt) ];
        static::$i++;

        return [
            'evaluation_answer_id' => $a['answerId'],
            'evaluation_option_id'=> $a['optionId'],
        ];
    }
}
